version: 2
jobs:
  build:
    docker:
      - image: cibuilds/hugo:latest
    working_directory: ~/hugo
    environment:
      HUGO_BUILD_DIR: ~/hugo/public

    steps:
      - run: apk update && apk add git
      - add_ssh_keys:
          fingerprints:
            - "42:41:dd:4c:24:92:49:91:73:0c:71:de:54:66:be:61"
      - checkout
      # install git submodules for managing third-party dependencies
      - run: git submodule sync && git submodule update --init

      # build with Hugo
      - run: HUGO_ENV=production hugo -v -d $HUGO_BUILD_DIR

      - run:
          name: test our generated HTML files
          command: |
            htmlproofer $HUGO_BUILD_DIR --allow-hash-href --check-html \
            --empty-alt-ignore --disable-external
      - deploy:
          name: Deploy to Github Pages
          working_directory: ~/public
          command: |
            git config credential.helper 'cache --timeout=120'
            git config user.email "uzi@smallandsole.com"
            git config user.name "ahimsauzi"
            git add .
            git commit --allow-empty -m "Trigger hugo deployment"
            git push -q git@github.com:ahimsauzi/ahimsauzi.github.io.git master

workflows:
  version: 2
  main:
    jobs:
      - build:
          filters:
            branches:
              only: gh-pages